# WAP to create a matrix of N x N dimension
# using next() + itertools.count()
import itertools

n = int(input('Enter the dimension: '))
print(f'The dimension is {n}')

temp = itertools.count(1)
res = [[next(temp) for i in range(n)] for i in range(n)]

# print result
for i in range(n):
    for j in range(n):
        print(res[i][j], end=" ")
    print()

'''
next is a built-in function in Python that retrieves the next item from an iterator. 
temp is an iterator generated by the itertools.count(1) function, 
which generates a sequence of numbers starting from 1. 
The next function is used to retrieve the next number from this sequence, 
and this number is used to fill a specific cell in the matrix. 
The next function is called n times for each row in the matrix, which creates a matrix of size n x n
'''